package template

type GCP struct {
	ModuleSource                           string `hcl:"source" default:"dcos-terraform/dcos/gcp" json:"source"`
	ModuleVersion                          string `hcl:"version" default:"~> 0.2.1" json:"version"`
	ClusterName                            string `hcl:"cluster_name" hcle:"omitempty" json:"cluster_name,omitempty"`
	SshPublicKey                           string `hcl:"ssh_public_key" hcle:"omitempty" json:"ssh_public_key,omitempty"`
	SshPublicKeyFile                       string `hcl:"ssh_public_key_file" json:"ssh_public_key_file"`
	NumMasters                             string `hcl:"num_masters" hcle:"omitempty" json:"num_masters,omitempty"`
	NumPrivateAgents                       string `hcl:"num_private_agents" hcle:"omitempty" json:"num_private_agents,omitempty"`
	NumPublicAgents                        string `hcl:"num_public_agents" hcle:"omitempty" json:"num_public_agents,omitempty"`
	Labels                                 string `hcl:"labels" hcle:"omitempty" json:"labels,omitempty"`
	AdminIps                               string `hcl:"admin_ips" json:"admin_ips"`
	AvailabilityZones                      string `hcl:"availability_zones" hcle:"omitempty" json:"availability_zones,omitempty"`
	DcosInstanceOs                         string `hcl:"dcos_instance_os" hcle:"omitempty" json:"dcos_instance_os,omitempty"`
	BootstrapGcpImage                      string `hcl:"bootstrap_gcp_image" hcle:"omitempty" json:"bootstrap_gcp_image,omitempty"`
	BootstrapOs                            string `hcl:"bootstrap_os" hcle:"omitempty" json:"bootstrap_os,omitempty"`
	BootstrapRootVolumeSize                string `hcl:"bootstrap_root_volume_size" hcle:"omitempty" json:"bootstrap_root_volume_size,omitempty"`
	BootstrapRootVolumeType                string `hcl:"bootstrap_root_volume_type" hcle:"omitempty" json:"bootstrap_root_volume_type,omitempty"`
	BootstrapMachineType                   string `hcl:"bootstrap_machine_type" hcle:"omitempty" json:"bootstrap_machine_type,omitempty"`
	MastersGcpImage                        string `hcl:"masters_gcp_image" hcle:"omitempty" json:"masters_gcp_image,omitempty"`
	MastersOs                              string `hcl:"masters_os" hcle:"omitempty" json:"masters_os,omitempty"`
	MastersRootVolumeSize                  string `hcl:"masters_root_volume_size" hcle:"omitempty" json:"masters_root_volume_size,omitempty"`
	MastersMachineType                     string `hcl:"masters_machine_type" hcle:"omitempty" json:"masters_machine_type,omitempty"`
	PrivateAgentsGcpImage                  string `hcl:"private_agents_gcp_image" hcle:"omitempty" json:"private_agents_gcp_image,omitempty"`
	PrivateAgentsOs                        string `hcl:"private_agents_os" hcle:"omitempty" json:"private_agents_os,omitempty"`
	PrivateAgentsRootVolumeSize            string `hcl:"private_agents_root_volume_size" hcle:"omitempty" json:"private_agents_root_volume_size,omitempty"`
	PrivateAgentsRootVolumeType            string `hcl:"private_agents_root_volume_type" hcle:"omitempty" json:"private_agents_root_volume_type,omitempty"`
	PrivateAgentsMachineType               string `hcl:"private_agents_machine_type" hcle:"omitempty" json:"private_agents_machine_type,omitempty"`
	PublicAgentsGcpImage                   string `hcl:"public_agents_gcp_image" hcle:"omitempty" json:"public_agents_gcp_image,omitempty"`
	PublicAgentsOs                         string `hcl:"public_agents_os" hcle:"omitempty" json:"public_agents_os,omitempty"`
	PublicAgentsRootVolumeSize             string `hcl:"public_agents_root_volume_size" hcle:"omitempty" json:"public_agents_root_volume_size,omitempty"`
	PublicAgentsRootVolumeType             string `hcl:"public_agents_root_volume_type" hcle:"omitempty" json:"public_agents_root_volume_type,omitempty"`
	PublicAgentsMachineType                string `hcl:"public_agents_machine_type" hcle:"omitempty" json:"public_agents_machine_type,omitempty"`
	PublicAgentsAdditionalPorts            string `hcl:"public_agents_additional_ports" hcle:"omitempty" json:"public_agents_additional_ports,omitempty"`
	PublicAgentsAccessIps                  string `hcl:"public_agents_access_ips" hcle:"omitempty" json:"public_agents_access_ips,omitempty"`
	ClusterNameRandomString                string `hcl:"cluster_name_random_string" hcle:"omitempty" json:"cluster_name_random_string,omitempty"`
	AcceptedInternalNetworks               string `hcl:"accepted_internal_networks" hcle:"omitempty" json:"accepted_internal_networks,omitempty"`
	SubnetRange                            string `hcl:"subnet_range" hcle:"omitempty" json:"subnet_range,omitempty"`
	AdditionalPublicAgentIps               string `hcl:"additional_public_agent_ips" hcle:"omitempty" json:"additional_public_agent_ips,omitempty"`
	AdditionalPrivateAgentIps              string `hcl:"additional_private_agent_ips" hcle:"omitempty" json:"additional_private_agent_ips,omitempty"`
	AnsibleBundledContainer                string `hcl:"ansible_bundled_container" hcle:"omitempty" json:"ansible_bundled_container,omitempty"`
	AnsibleAdditionalConfig                string `hcl:"ansible_additional_config" hcle:"omitempty" json:"ansible_additional_config,omitempty"`
	DcosVariant                            string `hcl:"dcos_variant" hcle:"omitempty" json:"dcos_variant,omitempty"`
	BootstrapPrivateIp                     string `hcl:"bootstrap_private_ip" hcle:"omitempty" json:"bootstrap_private_ip,omitempty"`
	DcosVersion                            string `hcl:"dcos_version" hcle:"omitempty" json:"dcos_version,omitempty"`
	DcosSecurity                           string `hcl:"dcos_security" hcle:"omitempty" json:"dcos_security,omitempty"`
	DcosResolvers                          string `hcl:"dcos_resolvers" hcle:"omitempty" json:"dcos_resolvers,omitempty"`
	DcosSkipChecks                         string `hcl:"dcos_skip_checks" hcle:"omitempty" json:"dcos_skip_checks,omitempty"`
	DcosOauthEnabled                       string `hcl:"dcos_oauth_enabled" hcle:"omitempty" json:"dcos_oauth_enabled,omitempty"`
	DcosMasterExternalLoadbalancer         string `hcl:"dcos_master_external_loadbalancer" hcle:"omitempty" json:"dcos_master_external_loadbalancer,omitempty"`
	DcosMasterDiscovery                    string `hcl:"dcos_master_discovery" hcle:"omitempty" json:"dcos_master_discovery,omitempty"`
	DcosAwsTemplateStorageBucket           string `hcl:"dcos_aws_template_storage_bucket" hcle:"omitempty" json:"dcos_aws_template_storage_bucket,omitempty"`
	DcosAwsTemplateStorageBucketPath       string `hcl:"dcos_aws_template_storage_bucket_path" hcle:"omitempty" json:"dcos_aws_template_storage_bucket_path,omitempty"`
	DcosAwsTemplateStorageRegionName       string `hcl:"dcos_aws_template_storage_region_name" hcle:"omitempty" json:"dcos_aws_template_storage_region_name,omitempty"`
	DcosAwsTemplateUpload                  string `hcl:"dcos_aws_template_upload" hcle:"omitempty" json:"dcos_aws_template_upload,omitempty"`
	DcosAwsTemplateStorageAccessKeyId      string `hcl:"dcos_aws_template_storage_access_key_id" hcle:"omitempty" json:"dcos_aws_template_storage_access_key_id,omitempty"`
	DcosAwsTemplateStorageSecretAccessKey  string `hcl:"dcos_aws_template_storage_secret_access_key" hcle:"omitempty" json:"dcos_aws_template_storage_secret_access_key,omitempty"`
	DcosExhibitorStorageBackend            string `hcl:"dcos_exhibitor_storage_backend" hcle:"omitempty" json:"dcos_exhibitor_storage_backend,omitempty"`
	DcosExhibitorZkHosts                   string `hcl:"dcos_exhibitor_zk_hosts" hcle:"omitempty" json:"dcos_exhibitor_zk_hosts,omitempty"`
	DcosExhibitorZkPath                    string `hcl:"dcos_exhibitor_zk_path" hcle:"omitempty" json:"dcos_exhibitor_zk_path,omitempty"`
	DcosAwsAccessKeyId                     string `hcl:"dcos_aws_access_key_id" hcle:"omitempty" json:"dcos_aws_access_key_id,omitempty"`
	DcosAwsRegion                          string `hcl:"dcos_aws_region" hcle:"omitempty" json:"dcos_aws_region,omitempty"`
	DcosAwsSecretAccessKey                 string `hcl:"dcos_aws_secret_access_key" hcle:"omitempty" json:"dcos_aws_secret_access_key,omitempty"`
	DcosExhibitorExplicitKeys              string `hcl:"dcos_exhibitor_explicit_keys" hcle:"omitempty" json:"dcos_exhibitor_explicit_keys,omitempty"`
	DcosS3Bucket                           string `hcl:"dcos_s3_bucket" hcle:"omitempty" json:"dcos_s3_bucket,omitempty"`
	DcosS3Prefix                           string `hcl:"dcos_s3_prefix" hcle:"omitempty" json:"dcos_s3_prefix,omitempty"`
	DcosExhibitorAzureAccountName          string `hcl:"dcos_exhibitor_azure_account_name" hcle:"omitempty" json:"dcos_exhibitor_azure_account_name,omitempty"`
	DcosExhibitorAzureAccountKey           string `hcl:"dcos_exhibitor_azure_account_key" hcle:"omitempty" json:"dcos_exhibitor_azure_account_key,omitempty"`
	DcosExhibitorAzurePrefix               string `hcl:"dcos_exhibitor_azure_prefix" hcle:"omitempty" json:"dcos_exhibitor_azure_prefix,omitempty"`
	DcosExhibitorAddress                   string `hcl:"dcos_exhibitor_address" hcle:"omitempty" json:"dcos_exhibitor_address,omitempty"`
	NumOfPublicAgents                      string `hcl:"num_of_public_agents" hcle:"omitempty" json:"num_of_public_agents,omitempty"`
	NumOfPrivateAgents                     string `hcl:"num_of_private_agents" hcle:"omitempty" json:"num_of_private_agents,omitempty"`
	DcosNumMasters                         string `hcl:"dcos_num_masters" hcle:"omitempty" json:"dcos_num_masters,omitempty"`
	DcosCustomerKey                        string `hcl:"dcos_customer_key" hcle:"omitempty" json:"dcos_customer_key,omitempty"`
	DcosRexrayConfigMethod                 string `hcl:"dcos_rexray_config_method" hcle:"omitempty" json:"dcos_rexray_config_method,omitempty"`
	DcosRexrayConfigFilename               string `hcl:"dcos_rexray_config_filename" hcle:"omitempty" json:"dcos_rexray_config_filename,omitempty"`
	DcosAdminrouterTls10Enabled            string `hcl:"dcos_adminrouter_tls_1_0_enabled" hcle:"omitempty" json:"dcos_adminrouter_tls_1_0_enabled,omitempty"`
	DcosAdminrouterTls11Enabled            string `hcl:"dcos_adminrouter_tls_1_1_enabled" hcle:"omitempty" json:"dcos_adminrouter_tls_1_1_enabled,omitempty"`
	DcosAdminrouterTls12Enabled            string `hcl:"dcos_adminrouter_tls_1_2_enabled" hcle:"omitempty" json:"dcos_adminrouter_tls_1_2_enabled,omitempty"`
	DcosAdminrouterTlsCipherSuite          string `hcl:"dcos_adminrouter_tls_cipher_suite" hcle:"omitempty" json:"dcos_adminrouter_tls_cipher_suite,omitempty"`
	DcosAuthCookieSecureFlag               string `hcl:"dcos_auth_cookie_secure_flag" hcle:"omitempty" json:"dcos_auth_cookie_secure_flag,omitempty"`
	DcosBouncerExpirationAuthTokenDays     string `hcl:"dcos_bouncer_expiration_auth_token_days" hcle:"omitempty" json:"dcos_bouncer_expiration_auth_token_days,omitempty"`
	DcosSuperuserPasswordHash              string `hcl:"dcos_superuser_password_hash" hcle:"omitempty" json:"dcos_superuser_password_hash,omitempty"`
	DcosClusterName                        string `hcl:"dcos_cluster_name" hcle:"omitempty" json:"dcos_cluster_name,omitempty"`
	DcosCaCertificateChainPath             string `hcl:"dcos_ca_certificate_chain_path" hcle:"omitempty" json:"dcos_ca_certificate_chain_path,omitempty"`
	DcosCaCertificatePath                  string `hcl:"dcos_ca_certificate_path" hcle:"omitempty" json:"dcos_ca_certificate_path,omitempty"`
	DcosCaCertificateKeyPath               string `hcl:"dcos_ca_certificate_key_path" hcle:"omitempty" json:"dcos_ca_certificate_key_path,omitempty"`
	DcosConfig                             string `hcl:"dcos_config" hcle:"omitempty" json:"dcos_config,omitempty"`
	DcosCustomChecks                       string `hcl:"dcos_custom_checks" hcle:"omitempty" json:"dcos_custom_checks,omitempty"`
	DcosDnsBindIpBlacklist                 string `hcl:"dcos_dns_bind_ip_blacklist" hcle:"omitempty" json:"dcos_dns_bind_ip_blacklist,omitempty"`
	DcosEnableGpuIsolation                 string `hcl:"dcos_enable_gpu_isolation" hcle:"omitempty" json:"dcos_enable_gpu_isolation,omitempty"`
	DcosFaultDomainDetectContents          string `hcl:"dcos_fault_domain_detect_contents" hcle:"omitempty" json:"dcos_fault_domain_detect_contents,omitempty"`
	DcosFaultDomainEnabled                 string `hcl:"dcos_fault_domain_enabled" hcle:"omitempty" json:"dcos_fault_domain_enabled,omitempty"`
	DcosGpusAreScarce                      string `hcl:"dcos_gpus_are_scarce" hcle:"omitempty" json:"dcos_gpus_are_scarce,omitempty"`
	DcosL4LbEnableIpv6                     string `hcl:"dcos_l4lb_enable_ipv6" hcle:"omitempty" json:"dcos_l4lb_enable_ipv6,omitempty"`
	DcosLicenseKeyContents                 string `hcl:"dcos_license_key_contents" hcle:"omitempty" json:"dcos_license_key_contents,omitempty"`
	DcosMesosContainerLogSink              string `hcl:"dcos_mesos_container_log_sink" hcle:"omitempty" json:"dcos_mesos_container_log_sink,omitempty"`
	DcosMesosDnsSetTruncateBit             string `hcl:"dcos_mesos_dns_set_truncate_bit" hcle:"omitempty" json:"dcos_mesos_dns_set_truncate_bit,omitempty"`
	DcosMesosMaxCompletedTasksPerFramework string `hcl:"dcos_mesos_max_completed_tasks_per_framework" hcle:"omitempty" json:"dcos_mesos_max_completed_tasks_per_framework,omitempty"`
	DcosUcrDefaultBridgeSubnet             string `hcl:"dcos_ucr_default_bridge_subnet" hcle:"omitempty" json:"dcos_ucr_default_bridge_subnet,omitempty"`
	DcosSuperuserUsername                  string `hcl:"dcos_superuser_username" hcle:"omitempty" json:"dcos_superuser_username,omitempty"`
	DcosTelemetryEnabled                   string `hcl:"dcos_telemetry_enabled" hcle:"omitempty" json:"dcos_telemetry_enabled,omitempty"`
	DcosZkSuperCredentials                 string `hcl:"dcos_zk_super_credentials" hcle:"omitempty" json:"dcos_zk_super_credentials,omitempty"`
	DcosZkMasterCredentials                string `hcl:"dcos_zk_master_credentials" hcle:"omitempty" json:"dcos_zk_master_credentials,omitempty"`
	DcosZkAgentCredentials                 string `hcl:"dcos_zk_agent_credentials" hcle:"omitempty" json:"dcos_zk_agent_credentials,omitempty"`
	DcosOverlayEnable                      string `hcl:"dcos_overlay_enable" hcle:"omitempty" json:"dcos_overlay_enable,omitempty"`
	DcosOverlayConfigAttempts              string `hcl:"dcos_overlay_config_attempts" hcle:"omitempty" json:"dcos_overlay_config_attempts,omitempty"`
	DcosOverlayMtu                         string `hcl:"dcos_overlay_mtu" hcle:"omitempty" json:"dcos_overlay_mtu,omitempty"`
	DcosOverlayNetwork                     string `hcl:"dcos_overlay_network" hcle:"omitempty" json:"dcos_overlay_network,omitempty"`
	DcosDnsSearch                          string `hcl:"dcos_dns_search" hcle:"omitempty" json:"dcos_dns_search,omitempty"`
	DcosDnsForwardZones                    string `hcl:"dcos_dns_forward_zones" hcle:"omitempty" json:"dcos_dns_forward_zones,omitempty"`
	DcosMasterDnsBindall                   string `hcl:"dcos_master_dns_bindall" hcle:"omitempty" json:"dcos_master_dns_bindall,omitempty"`
	DcosUseProxy                           string `hcl:"dcos_use_proxy" hcle:"omitempty" json:"dcos_use_proxy,omitempty"`
	DcosHttpProxy                          string `hcl:"dcos_http_proxy" hcle:"omitempty" json:"dcos_http_proxy,omitempty"`
	DcosHttpsProxy                         string `hcl:"dcos_https_proxy" hcle:"omitempty" json:"dcos_https_proxy,omitempty"`
	DcosNoProxy                            string `hcl:"dcos_no_proxy" hcle:"omitempty" json:"dcos_no_proxy,omitempty"`
	DcosCheckTime                          string `hcl:"dcos_check_time" hcle:"omitempty" json:"dcos_check_time,omitempty"`
	DcosDockerRemoveDelay                  string `hcl:"dcos_docker_remove_delay" hcle:"omitempty" json:"dcos_docker_remove_delay,omitempty"`
	DcosAuditLogging                       string `hcl:"dcos_audit_logging" hcle:"omitempty" json:"dcos_audit_logging,omitempty"`
	DcosGcDelay                            string `hcl:"dcos_gc_delay" hcle:"omitempty" json:"dcos_gc_delay,omitempty"`
	DcosLogDirectory                       string `hcl:"dcos_log_directory" hcle:"omitempty" json:"dcos_log_directory,omitempty"`
	DcosProcessTimeout                     string `hcl:"dcos_process_timeout" hcle:"omitempty" json:"dcos_process_timeout,omitempty"`
	DcosClusterDockerCredentials           string `hcl:"dcos_cluster_docker_credentials" hcle:"omitempty" json:"dcos_cluster_docker_credentials,omitempty"`
	DcosClusterDockerCredentialsDcosOwned  string `hcl:"dcos_cluster_docker_credentials_dcos_owned" hcle:"omitempty" json:"dcos_cluster_docker_credentials_dcos_owned,omitempty"`
	DcosClusterDockerCredentialsWriteToEtc string `hcl:"dcos_cluster_docker_credentials_write_to_etc" hcle:"omitempty" json:"dcos_cluster_docker_credentials_write_to_etc,omitempty"`
	DcosClusterDockerCredentialsEnabled    string `hcl:"dcos_cluster_docker_credentials_enabled" hcle:"omitempty" json:"dcos_cluster_docker_credentials_enabled,omitempty"`
	DcosMasterList                         string `hcl:"dcos_master_list" hcle:"omitempty" json:"dcos_master_list,omitempty"`
	DcosPublicAgentList                    string `hcl:"dcos_public_agent_list" hcle:"omitempty" json:"dcos_public_agent_list,omitempty"`
	DcosPreviousVersion                    string `hcl:"dcos_previous_version" hcle:"omitempty" json:"dcos_previous_version,omitempty"`
	DcosPreviousVersionMasterIndex         string `hcl:"dcos_previous_version_master_index" hcle:"omitempty" json:"dcos_previous_version_master_index,omitempty"`
	DcosAgentList                          string `hcl:"dcos_agent_list" hcle:"omitempty" json:"dcos_agent_list,omitempty"`
	DcosBootstrapPort                      string `hcl:"dcos_bootstrap_port" hcle:"omitempty" json:"dcos_bootstrap_port,omitempty"`
	DcosIpDetectPublicFilename             string `hcl:"dcos_ip_detect_public_filename" hcle:"omitempty" json:"dcos_ip_detect_public_filename,omitempty"`
	DcosIpDetectPublicContents             string `hcl:"dcos_ip_detect_public_contents" hcle:"omitempty" json:"dcos_ip_detect_public_contents,omitempty"`
	DcosIpDetectContents                   string `hcl:"dcos_ip_detect_contents" hcle:"omitempty" json:"dcos_ip_detect_contents,omitempty"`
	DcosRexrayConfig                       string `hcl:"dcos_rexray_config" hcle:"omitempty" json:"dcos_rexray_config,omitempty"`
	DcosClusterDockerRegistryUrl           string `hcl:"dcos_cluster_docker_registry_url" hcle:"omitempty" json:"dcos_cluster_docker_registry_url,omitempty"`
	CustomDcosDownloadPath                 string `hcl:"custom_dcos_download_path" hcle:"omitempty" json:"custom_dcos_download_path,omitempty"`
	DcosClusterDockerRegistryEnabled       string `hcl:"dcos_cluster_docker_registry_enabled" hcle:"omitempty" json:"dcos_cluster_docker_registry_enabled,omitempty"`
	DcosEnableDockerGc                     string `hcl:"dcos_enable_docker_gc" hcle:"omitempty" json:"dcos_enable_docker_gc,omitempty"`
	DcosStagedPackageStorageUri            string `hcl:"dcos_staged_package_storage_uri" hcle:"omitempty" json:"dcos_staged_package_storage_uri,omitempty"`
	DcosPackageStorageUri                  string `hcl:"dcos_package_storage_uri" hcle:"omitempty" json:"dcos_package_storage_uri,omitempty"`
	DcosEnableMesosInputPlugin             string `hcl:"dcos_enable_mesos_input_plugin" hcle:"omitempty" json:"dcos_enable_mesos_input_plugin,omitempty"`
}
